
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 28 18:13:17 CST 2016
//----------------------------------------------------

package com.jordanec.calcjec;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HELP = 21;
  public static final int VALI = 30;
  public static final int VERS = 22;
  public static final int LESS_EQUAL = 12;
  public static final int LEFT_PAREN = 16;
  public static final int LIST = 26;
  public static final int EQUAL = 15;
  public static final int LIMP = 23;
  public static final int DIVISION = 5;
  public static final int SUM = 2;
  public static final int IDENTIFIER = 31;
  public static final int GREATER_EQUAL = 13;
  public static final int NOT_EQUAL = 14;
  public static final int POW = 6;
  public static final int GREATER = 11;
  public static final int CALC = 27;
  public static final int BOOLEAN = 20;
  public static final int CONDITIONAL = 9;
  public static final int FLOAT = 19;
  public static final int DEFI = 25;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int SUBTRACTION = 3;
  public static final int MULTIPLICATION = 4;
  public static final int GRAB = 29;
  public static final int BORR = 28;
  public static final int error = 1;
  public static final int SQUARE_ROOT = 7;
  public static final int ASSIGN = 8;
  public static final int RIGHT_PAREN = 17;
  public static final int TERM = 24;
  public static final int LESS = 10;
}

