
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 25 18:50:57 CST 2016
//----------------------------------------------------

package com.jordanec.calcjec;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HELP = 14;
  public static final int VALI = 23;
  public static final int VERS = 15;
  public static final int LEFT_PAREN = 9;
  public static final int LIST = 19;
  public static final int LIMP = 16;
  public static final int DIVISION = 5;
  public static final int SUM = 2;
  public static final int IDENTIFIER = 24;
  public static final int POW = 6;
  public static final int CALC = 20;
  public static final int BOOLEAN = 13;
  public static final int FLOAT = 12;
  public static final int DEFI = 18;
  public static final int EOF = 0;
  public static final int SUBTRACTION = 3;
  public static final int NUMBER = 11;
  public static final int MULTIPLICATION = 4;
  public static final int GRAB = 22;
  public static final int BORR = 21;
  public static final int error = 1;
  public static final int SQUARE_ROOT = 7;
  public static final int ASSIGN = 8;
  public static final int RIGHT_PAREN = 10;
  public static final int TERM = 17;
}

