
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 28 18:31:06 CST 2016
//----------------------------------------------------

package com.jordanec.calcjec;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HELP = 15;
  public static final int VALI = 24;
  public static final int RELATIONAL = 26;
  public static final int VERS = 16;
  public static final int LEFT_PAREN = 10;
  public static final int LIST = 20;
  public static final int LIMP = 17;
  public static final int DIVISION = 5;
  public static final int SUM = 2;
  public static final int IDENTIFIER = 25;
  public static final int POW = 6;
  public static final int CALC = 21;
  public static final int CONDITIONAL = 9;
  public static final int BOOLEAN = 14;
  public static final int FLOAT = 13;
  public static final int DEFI = 19;
  public static final int EOF = 0;
  public static final int SUBTRACTION = 3;
  public static final int NUMBER = 12;
  public static final int MULTIPLICATION = 4;
  public static final int GRAB = 23;
  public static final int BORR = 22;
  public static final int error = 1;
  public static final int SQUARE_ROOT = 7;
  public static final int ASSIGN = 8;
  public static final int RIGHT_PAREN = 11;
  public static final int TERM = 18;
}

